name: Kernel Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP by ${{ github.actor }}
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16

    - name: Build
      run: |
        ./build_kernel_GKI.sh

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          AnyKernel3/m55xq-AnyKernel3.zip
        name: Unofficial Kernel Build for M55XQ (Samsung)
        tag_name: ${{ github.run_id }}-M55XQ
        body: |
          Build_ID: ${{ github.run_id }}
          Device: M55XQ (Samsung)
